plugins {
  id("awesome.androidapp.plugin")
}

dependencies {
    
    implementation(project(":layer_4:module_4_75"))
    implementation(project(":layer_4:module_4_76"))
    implementation(project(":layer_4:module_4_77"))
    implementation(project(":layer_4:module_4_78"))
    implementation(project(":layer_4:module_4_79"))
    implementation(project(":layer_4:module_4_80"))
    implementation(project(":layer_4:module_4_81"))
    implementation(project(":layer_4:module_4_82"))
    implementation(project(":layer_4:module_4_83"))
    implementation(project(":layer_4:module_4_84"))
    implementation(project(":layer_4:module_4_85"))
    implementation(project(":layer_4:module_4_86"))
    implementation(project(":layer_4:module_4_87"))
    implementation(project(":layer_4:module_4_75"))
    implementation(project(":layer_4:module_4_76"))
    implementation(project(":layer_4:module_4_77"))
    implementation(project(":layer_4:module_4_78"))
    implementation(project(":layer_4:module_4_79"))
    implementation(project(":layer_4:module_4_80"))
    implementation(project(":layer_4:module_4_81"))
    implementation(project(":layer_4:module_4_82"))
    implementation(project(":layer_4:module_4_83"))
    implementation(project(":layer_4:module_4_84"))
    implementation(project(":layer_4:module_4_85"))
    implementation(project(":layer_4:module_4_86"))
    implementation(project(":layer_4:module_4_87"))
implementation("androidx.core:core-ktx:1.12.0")
implementation("androidx.appcompat:appcompat:1.6.1")
implementation("com.google.android.material:material:1.11.0")
implementation("androidx.constraintlayout:constraintlayout:2.1.4")
implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-service:2.7.0")
implementation("androidx.fragment:fragment-ktx:1.6.2")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

// Compose dependencies
implementation(platform("androidx.compose:compose-bom:2024.02.00"))
implementation("androidx.compose.ui:ui")
implementation("androidx.compose.ui:ui-graphics")
implementation("androidx.compose.ui:ui-tooling-preview")
implementation("androidx.compose.material3:material3")
implementation("androidx.compose.runtime:runtime")
implementation("androidx.compose.runtime:runtime-livedata")
implementation("androidx.activity:activity-compose:1.8.2")
implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
debugImplementation("androidx.compose.ui:ui-tooling")
debugImplementation("androidx.compose.ui:ui-test-manifest")

// Network dependencies
implementation("com.squareup.retrofit2:retrofit:2.9.0")
implementation("com.squareup.retrofit2:converter-gson:2.9.0")
implementation("com.squareup.okhttp3:okhttp:4.12.0")
implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
}
        