plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_1:module_1_198"))
    implementation(project(":layer_1:module_1_168"))
    implementation(project(":layer_1:module_1_142"))
    implementation(project(":layer_1:module_1_167"))
    implementation(project(":layer_1:module_1_193"))
    implementation(project(":layer_1:module_1_154"))
    implementation(project(":layer_1:module_1_175"))
    implementation(project(":layer_1:module_1_148"))
    implementation(project(":layer_1:module_1_162"))
    implementation(project(":layer_1:module_1_195"))
    implementation(project(":layer_1:module_1_184"))
    implementation(project(":layer_1:module_1_176"))
    implementation(project(":layer_1:module_1_197"))
    implementation(project(":layer_1:module_1_158"))
    implementation(project(":layer_1:module_1_139"))
    implementation(project(":layer_1:module_1_150"))
    implementation(project(":layer_1:module_1_160"))
    implementation(project(":layer_1:module_1_138"))
    implementation(project(":layer_1:module_1_136"))
    implementation(project(":layer_1:module_1_180"))
    implementation(project(":layer_1:module_1_178"))
    implementation(project(":layer_1:module_1_165"))
    implementation(project(":layer_1:module_1_152"))
    implementation(project(":layer_1:module_1_171"))
    implementation(project(":layer_1:module_1_135"))
    implementation(project(":layer_1:module_1_190"))
    implementation(project(":layer_1:module_1_163"))
    implementation(project(":layer_1:module_1_155"))
    implementation(project(":layer_1:module_1_181"))
    implementation(project(":layer_1:module_1_198"))
    implementation(project(":layer_1:module_1_168"))
    implementation(project(":layer_1:module_1_142"))
    implementation(project(":layer_1:module_1_167"))
    implementation(project(":layer_1:module_1_193"))
    implementation(project(":layer_1:module_1_154"))
    implementation(project(":layer_1:module_1_175"))
    implementation(project(":layer_1:module_1_148"))
    implementation(project(":layer_1:module_1_162"))
    implementation(project(":layer_1:module_1_195"))
    implementation(project(":layer_1:module_1_184"))
    implementation(project(":layer_1:module_1_176"))
    implementation(project(":layer_1:module_1_197"))
    implementation(project(":layer_1:module_1_158"))
    implementation(project(":layer_1:module_1_139"))
    implementation(project(":layer_1:module_1_150"))
    implementation(project(":layer_1:module_1_160"))
    implementation(project(":layer_1:module_1_138"))
    implementation(project(":layer_1:module_1_136"))
    implementation(project(":layer_1:module_1_180"))
    implementation(project(":layer_1:module_1_178"))
    implementation(project(":layer_1:module_1_165"))
    implementation(project(":layer_1:module_1_152"))
    implementation(project(":layer_1:module_1_171"))
    implementation(project(":layer_1:module_1_135"))
    implementation(project(":layer_1:module_1_190"))
    implementation(project(":layer_1:module_1_163"))
    implementation(project(":layer_1:module_1_155"))
    implementation(project(":layer_1:module_1_181"))
implementation("androidx.core:core-ktx:1.12.0")
implementation("androidx.appcompat:appcompat:1.6.1")
implementation("com.google.android.material:material:1.11.0")
implementation("androidx.constraintlayout:constraintlayout:2.1.4")
implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-service:2.7.0")
implementation("androidx.fragment:fragment-ktx:1.6.2")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

// Compose dependencies
implementation(platform("androidx.compose:compose-bom:2024.02.00"))
implementation("androidx.compose.ui:ui")
implementation("androidx.compose.ui:ui-graphics")
implementation("androidx.compose.ui:ui-tooling-preview")
implementation("androidx.compose.material3:material3")
implementation("androidx.compose.runtime:runtime")
implementation("androidx.compose.runtime:runtime-livedata")
implementation("androidx.activity:activity-compose:1.8.2")
implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
debugImplementation("androidx.compose.ui:ui-tooling")
debugImplementation("androidx.compose.ui:ui-test-manifest")

// Network dependencies
implementation("com.squareup.retrofit2:retrofit:2.9.0")
implementation("com.squareup.retrofit2:converter-gson:2.9.0")
implementation("com.squareup.okhttp3:okhttp:4.12.0")
implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
}
        