plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_1:module_1_123"))
    implementation(project(":layer_1:module_1_118"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_126"))
    implementation(project(":layer_1:module_1_115"))
    implementation(project(":layer_1:module_1_116"))
    implementation(project(":layer_1:module_1_95"))
    implementation(project(":layer_1:module_1_99"))
    implementation(project(":layer_1:module_1_129"))
    implementation(project(":layer_1:module_1_100"))
    implementation(project(":layer_1:module_1_109"))
    implementation(project(":layer_1:module_1_122"))
    implementation(project(":layer_1:module_1_110"))
    implementation(project(":layer_1:module_1_130"))
    implementation(project(":layer_1:module_1_91"))
    implementation(project(":layer_1:module_1_101"))
    implementation(project(":layer_1:module_1_102"))
    implementation(project(":layer_1:module_1_89"))
    implementation(project(":layer_1:module_1_131"))
    implementation(project(":layer_1:module_1_121"))
    implementation(project(":layer_1:module_1_113"))
    implementation(project(":layer_1:module_1_123"))
    implementation(project(":layer_1:module_1_118"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_126"))
    implementation(project(":layer_1:module_1_115"))
    implementation(project(":layer_1:module_1_116"))
    implementation(project(":layer_1:module_1_95"))
    implementation(project(":layer_1:module_1_99"))
    implementation(project(":layer_1:module_1_129"))
    implementation(project(":layer_1:module_1_100"))
    implementation(project(":layer_1:module_1_109"))
    implementation(project(":layer_1:module_1_122"))
    implementation(project(":layer_1:module_1_110"))
    implementation(project(":layer_1:module_1_130"))
    implementation(project(":layer_1:module_1_91"))
    implementation(project(":layer_1:module_1_101"))
    implementation(project(":layer_1:module_1_102"))
    implementation(project(":layer_1:module_1_89"))
    implementation(project(":layer_1:module_1_131"))
    implementation(project(":layer_1:module_1_121"))
    implementation(project(":layer_1:module_1_113"))
implementation("androidx.core:core-ktx:1.12.0")
implementation("androidx.appcompat:appcompat:1.6.1")
implementation("com.google.android.material:material:1.11.0")
implementation("androidx.constraintlayout:constraintlayout:2.1.4")
implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-service:2.7.0")
implementation("androidx.fragment:fragment-ktx:1.6.2")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

// Compose dependencies
implementation(platform("androidx.compose:compose-bom:2024.02.00"))
implementation("androidx.compose.ui:ui")
implementation("androidx.compose.ui:ui-graphics")
implementation("androidx.compose.ui:ui-tooling-preview")
implementation("androidx.compose.material3:material3")
implementation("androidx.compose.runtime:runtime")
implementation("androidx.compose.runtime:runtime-livedata")
implementation("androidx.activity:activity-compose:1.8.2")
implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
debugImplementation("androidx.compose.ui:ui-tooling")
debugImplementation("androidx.compose.ui:ui-test-manifest")

// Network dependencies
implementation("com.squareup.retrofit2:retrofit:2.9.0")
implementation("com.squareup.retrofit2:converter-gson:2.9.0")
implementation("com.squareup.okhttp3:okhttp:4.12.0")
implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
}
        