name: "Java Memory Monitor"
description: "Tracks memory usage of Gradle/Kotlin daemons during the job"

inputs:
    interval:
        description: "Polling interval in seconds"
        required: false
        default: "5"

runs:
    using: "node20"
    main: "dist/index.js"
    post: "dist/cleanup.js"

dependencies:
    - name: "@actions/core"
      version: "^1.10.1"
    - name: "@actions/exec"
      version: "^1.1.1"
