name: "Java Memory Monitor"
description: "Tracks memory usage of Gradle/Kotlin daemons during the job"

inputs:
    interval:
        description: "Polling interval in seconds"
        required: false
        default: "5"

runs:
    using: "composite"
    steps:
        - name: Start Java memory monitor
          shell: bash
          run: |
              chmod +x ${{ github.action_path }}/monitor.sh
              nohup ${{ github.action_path }}/monitor.sh "${{ inputs.interval }}" > java_mem_monitor.log 2>&1 &
              echo $! > monitor.pid

        - name: Register post cleanup step
          shell: bash
          run: |
              cat << 'EOF' > post-monitor.sh
              #!/bin/bash
              echo "Stopping Java memory monitor..."
              if [[ -f monitor.pid ]]; then
                kill "$(cat monitor.pid)" || true
              fi

              echo "### Java Memory Monitor Summary" >> $GITHUB_STEP_SUMMARY
              tail -n 20 java_mem_monitor.log >> $GITHUB_STEP_SUMMARY

              mkdir -p logs
              mv java_mem_monitor.log logs/
              EOF
              chmod +x post-monitor.sh
              echo "post-monitor.sh" >> $GITHUB_STATE
