plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_3:module_3_255"))
    implementation(project(":layer_3:module_3_266"))
    implementation(project(":layer_3:module_3_263"))
    implementation(project(":layer_3:module_3_265"))
    implementation(project(":layer_3:module_3_269"))
    implementation(project(":layer_3:module_3_272"))
    implementation(project(":layer_3:module_3_259"))
    implementation(project(":layer_3:module_3_271"))
    implementation(project(":layer_3:module_3_264"))
    implementation(project(":layer_3:module_3_252"))
    implementation(project(":layer_3:module_3_248"))
    implementation(project(":layer_3:module_3_253"))
    implementation(project(":layer_3:module_3_251"))
    implementation(project(":layer_3:module_3_247"))
    implementation(project(":layer_3:module_3_244"))
    implementation(project(":layer_3:module_3_262"))
    implementation(project(":layer_3:module_3_246"))
    implementation(project(":layer_3:module_3_245"))
    implementation(project(":layer_3:module_3_249"))
    implementation(project(":layer_3:module_3_258"))
    implementation(project(":layer_3:module_3_273"))
    implementation(project(":layer_3:module_3_270"))
    implementation(project(":layer_3:module_3_254"))
    implementation(project(":layer_3:module_3_274"))
    implementation(project(":layer_3:module_3_257"))
    implementation(project(":layer_3:module_3_260"))
    implementation(project(":layer_3:module_3_261"))
    implementation(project(":layer_3:module_3_268"))
    implementation(project(":layer_3:module_3_255"))
    implementation(project(":layer_3:module_3_266"))
    implementation(project(":layer_3:module_3_263"))
    implementation(project(":layer_3:module_3_265"))
    implementation(project(":layer_3:module_3_269"))
    implementation(project(":layer_3:module_3_272"))
    implementation(project(":layer_3:module_3_259"))
    implementation(project(":layer_3:module_3_271"))
    implementation(project(":layer_3:module_3_264"))
    implementation(project(":layer_3:module_3_252"))
    implementation(project(":layer_3:module_3_248"))
    implementation(project(":layer_3:module_3_253"))
    implementation(project(":layer_3:module_3_251"))
    implementation(project(":layer_3:module_3_247"))
    implementation(project(":layer_3:module_3_244"))
    implementation(project(":layer_3:module_3_262"))
    implementation(project(":layer_3:module_3_246"))
    implementation(project(":layer_3:module_3_245"))
    implementation(project(":layer_3:module_3_249"))
    implementation(project(":layer_3:module_3_258"))
    implementation(project(":layer_3:module_3_273"))
    implementation(project(":layer_3:module_3_270"))
    implementation(project(":layer_3:module_3_254"))
    implementation(project(":layer_3:module_3_274"))
    implementation(project(":layer_3:module_3_257"))
    implementation(project(":layer_3:module_3_260"))
    implementation(project(":layer_3:module_3_261"))
    implementation(project(":layer_3:module_3_268"))
implementation("androidx.core:core-ktx:1.12.0")
implementation("androidx.appcompat:appcompat:1.6.1")
implementation("com.google.android.material:material:1.11.0")
implementation("androidx.constraintlayout:constraintlayout:2.1.4")
implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-service:2.7.0")
implementation("androidx.fragment:fragment-ktx:1.6.2")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

// Compose dependencies
implementation(platform("androidx.compose:compose-bom:2024.02.00"))
implementation("androidx.compose.ui:ui")
implementation("androidx.compose.ui:ui-graphics")
implementation("androidx.compose.ui:ui-tooling-preview")
implementation("androidx.compose.material3:material3")
implementation("androidx.compose.runtime:runtime")
implementation("androidx.compose.runtime:runtime-livedata")
implementation("androidx.activity:activity-compose:1.8.2")
implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
debugImplementation("androidx.compose.ui:ui-tooling")
debugImplementation("androidx.compose.ui:ui-test-manifest")

// Network dependencies
implementation("com.squareup.retrofit2:retrofit:2.9.0")
implementation("com.squareup.retrofit2:converter-gson:2.9.0")
implementation("com.squareup.okhttp3:okhttp:4.12.0")
implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
}
        