plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_2:module_2_136"))
    implementation(project(":layer_2:module_2_144"))
    implementation(project(":layer_2:module_2_158"))
    implementation(project(":layer_2:module_2_137"))
    implementation(project(":layer_2:module_2_157"))
    implementation(project(":layer_2:module_2_154"))
    implementation(project(":layer_2:module_2_156"))
    implementation(project(":layer_2:module_2_145"))
    implementation(project(":layer_2:module_2_133"))
    implementation(project(":layer_2:module_2_138"))
    implementation(project(":layer_2:module_2_161"))
    implementation(project(":layer_2:module_2_162"))
    implementation(project(":layer_2:module_2_155"))
    implementation(project(":layer_2:module_2_160"))
    implementation(project(":layer_2:module_2_148"))
    implementation(project(":layer_2:module_2_153"))
    implementation(project(":layer_2:module_2_136"))
    implementation(project(":layer_2:module_2_144"))
    implementation(project(":layer_2:module_2_158"))
    implementation(project(":layer_2:module_2_137"))
    implementation(project(":layer_2:module_2_157"))
    implementation(project(":layer_2:module_2_154"))
    implementation(project(":layer_2:module_2_156"))
    implementation(project(":layer_2:module_2_145"))
    implementation(project(":layer_2:module_2_133"))
    implementation(project(":layer_2:module_2_138"))
    implementation(project(":layer_2:module_2_161"))
    implementation(project(":layer_2:module_2_162"))
    implementation(project(":layer_2:module_2_155"))
    implementation(project(":layer_2:module_2_160"))
    implementation(project(":layer_2:module_2_148"))
    implementation(project(":layer_2:module_2_153"))
implementation("androidx.core:core-ktx:1.12.0")
implementation("androidx.appcompat:appcompat:1.6.1")
implementation("com.google.android.material:material:1.11.0")
implementation("androidx.constraintlayout:constraintlayout:2.1.4")
implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-service:2.7.0")
implementation("androidx.fragment:fragment-ktx:1.6.2")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

// Compose dependencies
implementation(platform("androidx.compose:compose-bom:2024.02.00"))
implementation("androidx.compose.ui:ui")
implementation("androidx.compose.ui:ui-graphics")
implementation("androidx.compose.ui:ui-tooling-preview")
implementation("androidx.compose.material3:material3")
implementation("androidx.compose.runtime:runtime")
implementation("androidx.compose.runtime:runtime-livedata")
implementation("androidx.activity:activity-compose:1.8.2")
implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
debugImplementation("androidx.compose.ui:ui-tooling")
debugImplementation("androidx.compose.ui:ui-test-manifest")

// Network dependencies
implementation("com.squareup.retrofit2:retrofit:2.9.0")
implementation("com.squareup.retrofit2:converter-gson:2.9.0")
implementation("com.squareup.okhttp3:okhttp:4.12.0")
implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
}
        