plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_83"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_83"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_43"))
implementation("androidx.core:core-ktx:1.12.0")
implementation("androidx.appcompat:appcompat:1.6.1")
implementation("com.google.android.material:material:1.11.0")
implementation("androidx.constraintlayout:constraintlayout:2.1.4")
implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-service:2.7.0")
implementation("androidx.fragment:fragment-ktx:1.6.2")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

// Compose dependencies
implementation(platform("androidx.compose:compose-bom:2024.02.00"))
implementation("androidx.compose.ui:ui")
implementation("androidx.compose.ui:ui-graphics")
implementation("androidx.compose.ui:ui-tooling-preview")
implementation("androidx.compose.material3:material3")
implementation("androidx.compose.runtime:runtime")
implementation("androidx.compose.runtime:runtime-livedata")
implementation("androidx.activity:activity-compose:1.8.2")
implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
debugImplementation("androidx.compose.ui:ui-tooling")
debugImplementation("androidx.compose.ui:ui-test-manifest")

// Network dependencies
implementation("com.squareup.retrofit2:retrofit:2.9.0")
implementation("com.squareup.retrofit2:converter-gson:2.9.0")
implementation("com.squareup.okhttp3:okhttp:4.12.0")
implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
}
        