name: "Start Java Memory Monitor"
description: "Starts tracking memory usage of Gradle/Kotlin daemons"

inputs:
  interval:
    description: "Polling interval in seconds"
    required: false
    default: "5"

runs:
  using: "node20"
  main: "../dist/index.js"