plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_3:module_3_172"))
    implementation(project(":layer_3:module_3_178"))
    implementation(project(":layer_3:module_3_177"))
    implementation(project(":layer_3:module_3_176"))
    implementation(project(":layer_3:module_3_181"))
    implementation(project(":layer_3:module_3_165"))
    implementation(project(":layer_3:module_3_164"))
    implementation(project(":layer_3:module_3_173"))
    implementation(project(":layer_3:module_3_182"))
    implementation(project(":layer_3:module_3_180"))
    implementation(project(":layer_3:module_3_175"))
    implementation(project(":layer_3:module_3_183"))
    implementation(project(":layer_3:module_3_179"))
    implementation(project(":layer_3:module_3_168"))
    implementation(project(":layer_3:module_3_166"))
    implementation(project(":layer_3:module_3_169"))
    implementation(project(":layer_3:module_3_171"))
    implementation(project(":layer_3:module_3_174"))
    implementation(project(":layer_3:module_3_170"))
    implementation(project(":layer_3:module_3_172"))
    implementation(project(":layer_3:module_3_178"))
    implementation(project(":layer_3:module_3_177"))
    implementation(project(":layer_3:module_3_176"))
    implementation(project(":layer_3:module_3_181"))
    implementation(project(":layer_3:module_3_165"))
    implementation(project(":layer_3:module_3_164"))
    implementation(project(":layer_3:module_3_173"))
    implementation(project(":layer_3:module_3_182"))
    implementation(project(":layer_3:module_3_180"))
    implementation(project(":layer_3:module_3_175"))
    implementation(project(":layer_3:module_3_183"))
    implementation(project(":layer_3:module_3_179"))
    implementation(project(":layer_3:module_3_168"))
    implementation(project(":layer_3:module_3_166"))
    implementation(project(":layer_3:module_3_169"))
    implementation(project(":layer_3:module_3_171"))
    implementation(project(":layer_3:module_3_174"))
    implementation(project(":layer_3:module_3_170"))
implementation("androidx.core:core-ktx:1.12.0")
implementation("androidx.appcompat:appcompat:1.6.1")
implementation("com.google.android.material:material:1.11.0")
implementation("androidx.constraintlayout:constraintlayout:2.1.4")
implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-service:2.7.0")
implementation("androidx.fragment:fragment-ktx:1.6.2")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

// Compose dependencies
implementation(platform("androidx.compose:compose-bom:2024.02.00"))
implementation("androidx.compose.ui:ui")
implementation("androidx.compose.ui:ui-graphics")
implementation("androidx.compose.ui:ui-tooling-preview")
implementation("androidx.compose.material3:material3")
implementation("androidx.compose.runtime:runtime")
implementation("androidx.compose.runtime:runtime-livedata")
implementation("androidx.activity:activity-compose:1.8.2")
implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
debugImplementation("androidx.compose.ui:ui-tooling")
debugImplementation("androidx.compose.ui:ui-test-manifest")

// Network dependencies
implementation("com.squareup.retrofit2:retrofit:2.9.0")
implementation("com.squareup.retrofit2:converter-gson:2.9.0")
implementation("com.squareup.okhttp3:okhttp:4.12.0")
implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
}
        