name: "Java Memory Monitor Cleanup"
description: "Cleans up the Java memory monitor and generates a summary"

runs:
    using: "node20"
    main: "dist/index.js"

dependencies:
    - name: "@actions/core"
      version: "^1.10.1"
    - name: "@actions/exec"
      version: "^1.1.1" 