plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_88"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_86"))
    implementation(project(":layer_0:module_0_81"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_88"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_86"))
    implementation(project(":layer_0:module_0_81"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_17"))
implementation("androidx.core:core-ktx:1.12.0")
implementation("androidx.appcompat:appcompat:1.6.1")
implementation("com.google.android.material:material:1.11.0")
implementation("androidx.constraintlayout:constraintlayout:2.1.4")
implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
implementation("androidx.lifecycle:lifecycle-service:2.7.0")
implementation("androidx.fragment:fragment-ktx:1.6.2")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")

// Compose dependencies
implementation(platform("androidx.compose:compose-bom:2024.02.00"))
implementation("androidx.compose.ui:ui")
implementation("androidx.compose.ui:ui-graphics")
implementation("androidx.compose.ui:ui-tooling-preview")
implementation("androidx.compose.material3:material3")
implementation("androidx.compose.runtime:runtime")
implementation("androidx.compose.runtime:runtime-livedata")
implementation("androidx.activity:activity-compose:1.8.2")
implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
debugImplementation("androidx.compose.ui:ui-tooling")
debugImplementation("androidx.compose.ui:ui-test-manifest")

// Network dependencies
implementation("com.squareup.retrofit2:retrofit:2.9.0")
implementation("com.squareup.retrofit2:converter-gson:2.9.0")
implementation("com.squareup.okhttp3:okhttp:4.12.0")
implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
}
        